# Generated by Django 4.2.3 on 2023-08-10 19:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Modules",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("moduleId", models.CharField(max_length=250)),
                ("title", models.CharField(blank=True, max_length=250)),
                ("likeCount", models.IntegerField(default=0)),
                ("difficulty", models.IntegerField(default=0)),
                (
                    "image",
                    models.ImageField(
                        default="default.jpeg", upload_to="module_images"
                    ),
                ),
                (
                    "likes",
                    models.ManyToManyField(
                        blank=True,
                        default=None,
                        related_name="favourite",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
