# Generated by Django 4.2.3 on 2023-08-11 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="exclusive",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="exclusiveChecked",
            field=models.BooleanField(default=False),
        ),
    ]
